name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        working-directory: ./backend
        run: poetry install --no-root
      - name: Update poetry.lock
        working-directory: ./backend
        run: poetry lock --no-update
      - name: Lint with Black
        working-directory: ./backend
        run: poetry run black --check .
      - name: Lint with Bandit
        working-directory: ./backend
        run: poetry run bandit -r src
      - name: Test with Pytest
        working-directory: ./backend
        run: poetry run pytest
      - name: Docker Scout Scan
        run: |
          docker pull $(docker build -q ./backend)
          docker scout cves --image $(docker build -q ./backend)
      - name: Run pip-audit
        working-directory: ./backend
        run: pip install pip-audit && poetry export -f requirements.txt --output requirements.txt --without-hashes && pip-audit -r requirements.txt