name: Backend CD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Lowercase Repository Name
        id: get_repo_name
        run: echo "::set-output name=repo::$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"

      - name: Build and Push Backend Docker Image
        run: |
          docker build ./backend --tag ghcr.io/${{ steps.get_repo_name.outputs.repo }}/jobscraper-backend:latest
          docker push ghcr.io/${{ steps.get_repo_name.outputs.repo }}/jobscraper-backend:latest

      # This step is a placeholder for actual deployment to a Linux server via Cloudflare Tunnels.
      # In a real-world scenario, you would typically SSH into your server and run commands
      # to pull the new image and restart the Docker container.
      # This could involve:
      # - Setting up SSH keys as GitHub secrets
      # - Using a "ssh-action" to execute commands on the remote server
      # - Commands like `docker pull your-docker-username/jobscraper-backend:latest`
      # - And `docker-compose up -d` or `docker restart your-backend-container`
      - name: Placeholder for Server Deployment
        run: echo "Deployment to server via Cloudflare Tunnels would happen here."