name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_cd.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Frontend Docker Image
        run: |
          docker build ./frontend --tag ghcr.io/${{ lower(github.repository) }}/jobscraper-frontend:latest
          docker push ghcr.io/${{ lower(github.repository) }}/jobscraper-frontend:latest

      # This step is a placeholder for actual deployment to a Linux server via Cloudflare Tunnels.
      # In a real-world scenario, you would typically SSH into your server and run commands
      # to pull the new image and restart the Docker container.
      # This could involve:
      # - Setting up SSH keys as GitHub secrets
      # - Using a "ssh-action" to execute commands on the remote server
      # - Commands like `docker pull your-docker-username/jobscraper-frontend:latest`
      # - And `docker-compose up -d` or `docker restart your-frontend-container`
      - name: Placeholder for Server Deployment
        run: echo "Deployment to server via Cloudflare Tunnels would happen here."