name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Clean npm cache and install dependencies
        working-directory: ./frontend
        run: |
          npm cache clean --force
          npm install
      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint
      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false
      - name: Build production app
        working-directory: ./frontend
        run: npm run build